package Frontend;

import Backend.DB.DTO.Employee_DTO;
import Backend.Tools.Time;
import Frontend.Building.Inventary.Inventary_Content;
import Frontend.Building.Stowage.Stowage_Content;
import Frontend.Employee.Admin.Admin_Content;
import Frontend.Employee.SalesPerson.SalesPerson_Content;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author phily
 */
public class Home extends javax.swing.JFrame {
    private Admin_Content admin_C;
    private SalesPerson_Content salesPerson_C;
    private Inventary_Content inventary_C;
    private Stowage_Content stowage_C;   
    
    private Time time;
    
    private Employee_DTO employee;
    
    /**
     * Creates new form Home
     */
    public Home(Employee_DTO currentEmployee) {
        initComponents();
        
        this.employee = currentEmployee;
        this.time = new Time();
                
        this.setHeader();
        this.setInternalFrame();                
    }
    
    private void setInternalFrame(){
        if(employee.getContract().getPosition().equals("administrator")){
            this.admin_C = new Admin_Content(this.employee);
            this.Home_desktopPane.add(this.admin_C);
            this.admin_C.setVisible(true);
        }else if(employee.getContract().getPosition().equals("sales")){
            this.salesPerson_C = new SalesPerson_Content(this.employee);
            this.Home_desktopPane.add(this.salesPerson_C);
            this.salesPerson_C.setVisible(true);
        }else if(employee.getContract().getPosition().equals("inventary")){
            this.inventary_C = new Inventary_Content(this.employee);
            this.Home_desktopPane.add(this.inventary_C);
            this.inventary_C.setVisible(true);
        }else{
            this.stowage_C = new Stowage_Content(this.employee);
            this.Home_desktopPane.add(this.stowage_C);
            this.stowage_C.setVisible(true);
        }
    }
    
    private void setHeader(){
        this.txtF_name.setText(this.employee.getName());
        this.txtF_ID.setText(this.employee.getID());
        this.txtF_position.setText(this.employee.getContract().getPosition());
        this.txtF_office.setText(this.employee.getContract().getOffice());
        this.time.getTime(this.lbl_date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_employeeInfo = new javax.swing.JPanel();
        panel_photo = new javax.swing.JPanel();
        lbl_changeUser = new javax.swing.JLabel();
        lbl_employeeName = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        lbl_position = new javax.swing.JLabel();
        lbl_office = new javax.swing.JLabel();
        txtF_ID = new javax.swing.JTextField();
        txtF_name = new javax.swing.JTextField();
        txtF_position = new javax.swing.JTextField();
        txtF_office = new javax.swing.JTextField();
        lbl_date = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        Home_desktopPane = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel_employeeInfo.setBackground(new java.awt.Color(241, 244, 255));

        panel_photo.setBackground(new java.awt.Color(226, 231, 248));

        javax.swing.GroupLayout panel_photoLayout = new javax.swing.GroupLayout(panel_photo);
        panel_photo.setLayout(panel_photoLayout);
        panel_photoLayout.setHorizontalGroup(
            panel_photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
        );
        panel_photoLayout.setVerticalGroup(
            panel_photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        lbl_changeUser.setFont(new java.awt.Font("Khmer OS", 2, 12)); // NOI18N
        lbl_changeUser.setText("- Click to change user -");

        lbl_employeeName.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        lbl_employeeName.setText("Name:");

        lbl_ID.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        lbl_ID.setText("ID:");

        lbl_position.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        lbl_position.setText("Position:");

        lbl_office.setFont(new java.awt.Font("AnjaliOldLipi", 1, 15)); // NOI18N
        lbl_office.setText("Office:");

        txtF_ID.setEditable(false);
        txtF_ID.setFont(new java.awt.Font("Laksaman", 0, 13)); // NOI18N

        txtF_name.setEditable(false);
        txtF_name.setFont(new java.awt.Font("Laksaman", 0, 13)); // NOI18N

        txtF_position.setEditable(false);
        txtF_position.setFont(new java.awt.Font("Laksaman", 0, 13)); // NOI18N

        txtF_office.setEditable(false);
        txtF_office.setFont(new java.awt.Font("Laksaman", 0, 13)); // NOI18N

        lbl_date.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 13)); // NOI18N
        lbl_date.setText("Wednesday, March 8th 2023");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElectronicHome.jpg"))); // NOI18N

        javax.swing.GroupLayout panel_employeeInfoLayout = new javax.swing.GroupLayout(panel_employeeInfo);
        panel_employeeInfo.setLayout(panel_employeeInfoLayout);
        panel_employeeInfoLayout.setHorizontalGroup(
            panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(panel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lbl_changeUser)))
                .addGap(36, 36, 36)
                .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                        .addComponent(lbl_office)
                        .addGap(43, 43, 43)
                        .addComponent(txtF_office, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                        .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                                .addComponent(lbl_employeeName)
                                .addGap(43, 43, 43)
                                .addComponent(txtF_name, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_employeeInfoLayout.createSequentialGroup()
                                    .addComponent(lbl_position)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtF_position, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_employeeInfoLayout.createSequentialGroup()
                                    .addComponent(lbl_ID)
                                    .addGap(66, 66, 66)
                                    .addComponent(txtF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                        .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_logo)
                            .addComponent(lbl_date))))
                .addGap(19, 19, 19))
        );
        panel_employeeInfoLayout.setVerticalGroup(
            panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                        .addComponent(lbl_logo)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_date))
                    .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                        .addComponent(panel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_changeUser))
                    .addGroup(panel_employeeInfoLayout.createSequentialGroup()
                        .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_employeeName)
                            .addComponent(txtF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ID)
                            .addComponent(txtF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_position)
                            .addComponent(txtF_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_employeeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF_office, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_office))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Home_desktopPaneLayout = new javax.swing.GroupLayout(Home_desktopPane);
        Home_desktopPane.setLayout(Home_desktopPaneLayout);
        Home_desktopPaneLayout.setHorizontalGroup(
            Home_desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Home_desktopPaneLayout.setVerticalGroup(
            Home_desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_employeeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Home_desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_employeeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Home_desktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Home_desktopPane;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_changeUser;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_employeeName;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_office;
    private javax.swing.JLabel lbl_position;
    private javax.swing.JPanel panel_employeeInfo;
    private javax.swing.JPanel panel_photo;
    private javax.swing.JTextField txtF_ID;
    private javax.swing.JTextField txtF_name;
    private javax.swing.JTextField txtF_office;
    private javax.swing.JTextField txtF_position;
    // End of variables declaration//GEN-END:variables
}
