/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.Building.Store;

/**
 *
 * @author phily
 */
public class Store_Content extends javax.swing.JFrame {

    /**
     * Creates new form Store_Content
     */
    public Store_Content() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPan_inventoryOptions = new javax.swing.JTabbedPane();
        tab_requests = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_requests = new javax.swing.JTable();
        panel_options = new javax.swing.JPanel();
        lbl_title_requestCategories = new javax.swing.JLabel();
        txtF_read = new javax.swing.JTextField();
        txtF_processed = new javax.swing.JTextField();
        txtF_all = new javax.swing.JTextField();
        txtF_receved = new javax.swing.JTextField();
        lbl_to = new javax.swing.JLabel();
        llbl_date_to = new javax.swing.JLabel();
        button_search = new javax.swing.JButton();
        radioButton_requested = new javax.swing.JRadioButton();
        radioButton_all = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        radioButton_read = new javax.swing.JRadioButton();
        radioButton_processed = new javax.swing.JRadioButton();
        txtF_requested = new javax.swing.JTextField();
        lbl_from = new javax.swing.JLabel();
        lbl_date_since = new javax.swing.JLabel();
        cbBox_from = new javax.swing.JComboBox<>();
        cbBox_To = new javax.swing.JComboBox<>();
        spinner_since = new javax.swing.JSpinner();
        spinner_to = new javax.swing.JSpinner();
        tab_inventory = new javax.swing.JPanel();
        panel_searchOptions = new javax.swing.JPanel();
        lbl_inventaryStore = new javax.swing.JLabel();
        cbBox_inventaryStore = new javax.swing.JComboBox<>();
        radioButton_WhiteLine = new javax.swing.JRadioButton();
        lbl_inventaryCategory = new javax.swing.JLabel();
        radioButton_BrownLine = new javax.swing.JRadioButton();
        lbl_inventaryCode = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        btn_inventarySearch = new javax.swing.JButton();
        radioButton_EcoLine = new javax.swing.JRadioButton();
        lbl_inventaryType = new javax.swing.JLabel();
        cbBox_InventaryType = new javax.swing.JComboBox<>();
        lbl_inventaryBrand = new javax.swing.JLabel();
        cbBox_brand = new javax.swing.JComboBox<>();
        scrollPanel_inventaryDetails = new javax.swing.JScrollPane();
        table_inventaryDetails = new javax.swing.JTable();
        btn_transfer = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        panel_searchOptions1 = new javax.swing.JPanel();
        radioButton_store_WhiteLine = new javax.swing.JRadioButton();
        lbl_store_productCategory = new javax.swing.JLabel();
        radioButton_store_BrownLine = new javax.swing.JRadioButton();
        lbl_store_productCode = new javax.swing.JLabel();
        txt_store_productCode = new javax.swing.JTextField();
        btn_store_search = new javax.swing.JButton();
        radioButton_store_EcoLine = new javax.swing.JRadioButton();
        lbl_store_productType = new javax.swing.JLabel();
        cbBox_store_productType = new javax.swing.JComboBox<>();
        lbl_sore_productBrand = new javax.swing.JLabel();
        cbBox_store_productBrand = new javax.swing.JComboBox<>();
        scrollPanel_inventary_details = new javax.swing.JScrollPane();
        table_store_details = new javax.swing.JTable();
        btn_inventory_add = new javax.swing.JButton();

        table_requests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Date Requested", "Due Date", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_requests);

        lbl_title_requestCategories.setText("Request categories");

        txtF_read.setEditable(false);

        txtF_processed.setEditable(false);

        txtF_all.setEditable(false);

        txtF_receved.setEditable(false);

        lbl_to.setText("To:");

        llbl_date_to.setText("To:");

        button_search.setText("SEARCH");

        radioButton_requested.setText("Requested:");

        radioButton_all.setText("All:");

        jRadioButton3.setText("Received:");

        radioButton_read.setText("Read:");

        radioButton_processed.setText("Processed:");
        radioButton_processed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_processedActionPerformed(evt);
            }
        });

        txtF_requested.setEditable(false);

        lbl_from.setText("From:");

        lbl_date_since.setText("Since:");

        cbBox_from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de la tabla correspondiente" }));

        cbBox_To.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_optionsLayout = new javax.swing.GroupLayout(panel_options);
        panel_options.setLayout(panel_optionsLayout);
        panel_optionsLayout.setHorizontalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_title_requestCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(lbl_from)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbl_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbBox_To, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(lbl_date_since)
                                .addGap(31, 31, 31)
                                .addComponent(spinner_since, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(llbl_date_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinner_to, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(radioButton_requested, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtF_requested, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtF_read, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(radioButton_read, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtF_receved, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(radioButton_processed, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtF_processed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(radioButton_all)
                        .addGap(18, 18, 18)
                        .addComponent(txtF_all, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_search)))
                .addContainerGap())
        );
        panel_optionsLayout.setVerticalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_date_since)
                            .addComponent(spinner_since, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llbl_date_to)
                            .addComponent(spinner_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_from)
                            .addComponent(cbBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_to)
                            .addComponent(cbBox_To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_title_requestCategories)
                        .addGap(18, 18, 18)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_requested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioButton_requested)
                                    .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_read, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioButton_read)
                                    .addComponent(radioButton_processed)
                                    .addComponent(txtF_processed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioButton_all)
                                .addComponent(txtF_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtF_receved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout tab_requestsLayout = new javax.swing.GroupLayout(tab_requests);
        tab_requests.setLayout(tab_requestsLayout);
        tab_requestsLayout.setHorizontalGroup(
            tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_requestsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panel_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab_requestsLayout.setVerticalGroup(
            tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_requestsLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPan_inventoryOptions.addTab("Requests", tab_requests);

        lbl_inventaryStore.setText("Store:");

        cbBox_inventaryStore.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lo obtendrás de una tabla" }));

        radioButton_WhiteLine.setText("White line");

        lbl_inventaryCategory.setText("Category:");

        radioButton_BrownLine.setText("Brown line");

        lbl_inventaryCode.setText("Code:");

        btn_inventarySearch.setText("SEARCH");

        radioButton_EcoLine.setText("Eco line");

        lbl_inventaryType.setText("Type:");

        cbBox_InventaryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All (lo demás lo sacas de una tabla)" }));

        lbl_inventaryBrand.setText("Brand:");

        cbBox_brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de la tabla" }));

        javax.swing.GroupLayout panel_searchOptionsLayout = new javax.swing.GroupLayout(panel_searchOptions);
        panel_searchOptions.setLayout(panel_searchOptionsLayout);
        panel_searchOptionsLayout.setHorizontalGroup(
            panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                        .addComponent(lbl_inventaryCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_inventaryBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                        .addComponent(lbl_inventaryStore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBox_inventaryStore, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                        .addComponent(lbl_inventaryCategory)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_WhiteLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_BrownLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_EcoLine)
                        .addGap(41, 41, 41)
                        .addComponent(lbl_inventaryType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_InventaryType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_inventarySearch)))
                .addGap(6, 6, 6))
        );
        panel_searchOptionsLayout.setVerticalGroup(
            panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inventaryStore)
                    .addComponent(cbBox_inventaryStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inventaryCode)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inventaryBrand)
                    .addComponent(cbBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_inventarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_inventaryCategory)
                        .addComponent(radioButton_WhiteLine)
                        .addComponent(radioButton_BrownLine)
                        .addComponent(radioButton_EcoLine)
                        .addComponent(cbBox_InventaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_inventaryType)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        table_inventaryDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Brand", "StockID", "Price", "Avaible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel_inventaryDetails.setViewportView(table_inventaryDetails);

        btn_transfer.setText("Transfer");

        btn_add.setText("ADD");

        javax.swing.GroupLayout tab_inventoryLayout = new javax.swing.GroupLayout(tab_inventory);
        tab_inventory.setLayout(tab_inventoryLayout);
        tab_inventoryLayout.setHorizontalGroup(
            tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_searchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inventoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_transfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab_inventoryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPanel_inventaryDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );
        tab_inventoryLayout.setVerticalGroup(
            tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_inventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_searchOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
            .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inventoryLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(scrollPanel_inventaryDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        tabbedPan_inventoryOptions.addTab("Inventory", tab_inventory);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_searchOptions1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        radioButton_store_WhiteLine.setText("White line");

        lbl_store_productCategory.setText("Category:");

        radioButton_store_BrownLine.setText("Brown line");

        lbl_store_productCode.setText("Code:");

        btn_store_search.setText("SEARCH");

        radioButton_store_EcoLine.setText("Eco line");

        lbl_store_productType.setText("Type:");

        cbBox_store_productType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All (lo demás lo sacas de una tabla)" }));

        lbl_sore_productBrand.setText("Brand:");

        cbBox_store_productBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de la tabla" }));

        javax.swing.GroupLayout panel_searchOptions1Layout = new javax.swing.GroupLayout(panel_searchOptions1);
        panel_searchOptions1.setLayout(panel_searchOptions1Layout);
        panel_searchOptions1Layout.setHorizontalGroup(
            panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptions1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_searchOptions1Layout.createSequentialGroup()
                        .addComponent(lbl_store_productCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_store_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_sore_productBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_store_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_searchOptions1Layout.createSequentialGroup()
                        .addComponent(lbl_store_productCategory)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_store_WhiteLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_store_BrownLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_store_EcoLine)
                        .addGap(41, 41, 41)
                        .addComponent(lbl_store_productType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_store_productType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(361, 361, 361)
                .addComponent(btn_store_search, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_searchOptions1Layout.setVerticalGroup(
            panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptions1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_searchOptions1Layout.createSequentialGroup()
                        .addGroup(panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_store_productCode)
                            .addComponent(txt_store_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_sore_productBrand)
                            .addComponent(cbBox_store_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_store_productCategory)
                            .addComponent(radioButton_store_WhiteLine)
                            .addComponent(radioButton_store_BrownLine)
                            .addComponent(radioButton_store_EcoLine)
                            .addComponent(cbBox_store_productType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_store_productType))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_searchOptions1Layout.createSequentialGroup()
                        .addComponent(btn_store_search, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        table_store_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Brand", "StockID", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel_inventary_details.setViewportView(table_store_details);
        if (table_store_details.getColumnModel().getColumnCount() > 0) {
            table_store_details.getColumnModel().getColumn(0).setResizable(false);
            table_store_details.getColumnModel().getColumn(0).setPreferredWidth(70);
            table_store_details.getColumnModel().getColumn(1).setPreferredWidth(210);
            table_store_details.getColumnModel().getColumn(2).setResizable(false);
            table_store_details.getColumnModel().getColumn(2).setPreferredWidth(200);
            table_store_details.getColumnModel().getColumn(3).setResizable(false);
            table_store_details.getColumnModel().getColumn(3).setPreferredWidth(70);
            table_store_details.getColumnModel().getColumn(4).setResizable(false);
            table_store_details.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_store_details.getColumnModel().getColumn(5).setResizable(false);
            table_store_details.getColumnModel().getColumn(5).setPreferredWidth(70);
        }

        btn_inventory_add.setText("ADD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_searchOptions1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel_inventary_details, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_inventory_add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_searchOptions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btn_inventory_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(652, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPanel_inventary_details)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButton_processedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_processedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_processedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_inventarySearch;
    private javax.swing.JButton btn_inventory_add;
    private javax.swing.JButton btn_store_search;
    private javax.swing.JButton btn_transfer;
    private javax.swing.JButton button_search;
    private javax.swing.JComboBox<String> cbBox_InventaryType;
    private javax.swing.JComboBox<String> cbBox_To;
    private javax.swing.JComboBox<String> cbBox_brand;
    private javax.swing.JComboBox<String> cbBox_from;
    private javax.swing.JComboBox<String> cbBox_inventaryStore;
    private javax.swing.JComboBox<String> cbBox_store_productBrand;
    private javax.swing.JComboBox<String> cbBox_store_productType;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date_since;
    private javax.swing.JLabel lbl_from;
    private javax.swing.JLabel lbl_inventaryBrand;
    private javax.swing.JLabel lbl_inventaryCategory;
    private javax.swing.JLabel lbl_inventaryCode;
    private javax.swing.JLabel lbl_inventaryStore;
    private javax.swing.JLabel lbl_inventaryType;
    private javax.swing.JLabel lbl_sore_productBrand;
    private javax.swing.JLabel lbl_store_productCategory;
    private javax.swing.JLabel lbl_store_productCode;
    private javax.swing.JLabel lbl_store_productType;
    private javax.swing.JLabel lbl_title_requestCategories;
    private javax.swing.JLabel lbl_to;
    private javax.swing.JLabel llbl_date_to;
    private javax.swing.JPanel panel_options;
    private javax.swing.JPanel panel_searchOptions;
    private javax.swing.JPanel panel_searchOptions1;
    private javax.swing.JRadioButton radioButton_BrownLine;
    private javax.swing.JRadioButton radioButton_EcoLine;
    private javax.swing.JRadioButton radioButton_WhiteLine;
    private javax.swing.JRadioButton radioButton_all;
    private javax.swing.JRadioButton radioButton_processed;
    private javax.swing.JRadioButton radioButton_read;
    private javax.swing.JRadioButton radioButton_requested;
    private javax.swing.JRadioButton radioButton_store_BrownLine;
    private javax.swing.JRadioButton radioButton_store_EcoLine;
    private javax.swing.JRadioButton radioButton_store_WhiteLine;
    private javax.swing.JScrollPane scrollPanel_inventaryDetails;
    private javax.swing.JScrollPane scrollPanel_inventary_details;
    private javax.swing.JSpinner spinner_since;
    private javax.swing.JSpinner spinner_to;
    private javax.swing.JPanel tab_inventory;
    private javax.swing.JPanel tab_requests;
    private javax.swing.JTabbedPane tabbedPan_inventoryOptions;
    private javax.swing.JTable table_inventaryDetails;
    private javax.swing.JTable table_requests;
    private javax.swing.JTable table_store_details;
    private javax.swing.JTextField txtF_all;
    private javax.swing.JTextField txtF_processed;
    private javax.swing.JTextField txtF_read;
    private javax.swing.JTextField txtF_receved;
    private javax.swing.JTextField txtF_requested;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_store_productCode;
    // End of variables declaration//GEN-END:variables
}
