/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.Building.Inventary;

/**
 *
 * @author phily
 */
public class Inventary_Content extends javax.swing.JFrame {

    /**
     * Creates new form Inventary_Content
     */
    public Inventary_Content() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane_inventory_actions = new javax.swing.JTabbedPane();
        tab_requests = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_requests = new javax.swing.JTable();
        panel_options = new javax.swing.JPanel();
        lbl_title_requestCategories = new javax.swing.JLabel();
        txtF_read = new javax.swing.JTextField();
        txtF_processed = new javax.swing.JTextField();
        txtF_all = new javax.swing.JTextField();
        txtF_receved = new javax.swing.JTextField();
        lbl_to = new javax.swing.JLabel();
        llbl_date_to = new javax.swing.JLabel();
        button_search = new javax.swing.JButton();
        radioButton_requested = new javax.swing.JRadioButton();
        radioButton_all = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        radioButton_read = new javax.swing.JRadioButton();
        radioButton_processed = new javax.swing.JRadioButton();
        txtF_requested = new javax.swing.JTextField();
        lbl_from = new javax.swing.JLabel();
        lbl_date_since = new javax.swing.JLabel();
        cbBox_from = new javax.swing.JComboBox<>();
        cbBox_To = new javax.swing.JComboBox<>();
        spinner_since = new javax.swing.JSpinner();
        spinner_to = new javax.swing.JSpinner();
        tab_inventory = new javax.swing.JPanel();
        panel_searchOptions = new javax.swing.JPanel();
        lbl_inventary_store = new javax.swing.JLabel();
        cbBox_inventary_store = new javax.swing.JComboBox<>();
        radioButton_inventory_WhiteLine = new javax.swing.JRadioButton();
        lbl_inventary_productCategory = new javax.swing.JLabel();
        radioButton_inventary_BrownLine = new javax.swing.JRadioButton();
        lbl_inventary_productCode = new javax.swing.JLabel();
        txt_inventory_productCode = new javax.swing.JTextField();
        btn_inventary_search = new javax.swing.JButton();
        radioButton_inventory_EcoLine = new javax.swing.JRadioButton();
        lbl_inventary_productType = new javax.swing.JLabel();
        cbBox_inventary_productType = new javax.swing.JComboBox<>();
        lbl_inventary_productBrand = new javax.swing.JLabel();
        cbBox_inventory_productBrand = new javax.swing.JComboBox<>();
        scrollPanel_inventary_details = new javax.swing.JScrollPane();
        table_inventary_details = new javax.swing.JTable();
        btn_inventory_transfer = new javax.swing.JButton();
        btn_inventory_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        table_requests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Date Requested", "Due Date", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_requests);
        if (table_requests.getColumnModel().getColumnCount() > 0) {
            table_requests.getColumnModel().getColumn(0).setResizable(false);
            table_requests.getColumnModel().getColumn(0).setPreferredWidth(220);
            table_requests.getColumnModel().getColumn(1).setResizable(false);
            table_requests.getColumnModel().getColumn(1).setPreferredWidth(220);
            table_requests.getColumnModel().getColumn(2).setResizable(false);
            table_requests.getColumnModel().getColumn(2).setPreferredWidth(250);
            table_requests.getColumnModel().getColumn(3).setResizable(false);
            table_requests.getColumnModel().getColumn(3).setPreferredWidth(250);
            table_requests.getColumnModel().getColumn(4).setResizable(false);
            table_requests.getColumnModel().getColumn(4).setPreferredWidth(170);
        }

        lbl_title_requestCategories.setText("Request categories");

        txtF_read.setEditable(false);

        txtF_processed.setEditable(false);

        txtF_all.setEditable(false);

        txtF_receved.setEditable(false);

        lbl_to.setText("To:");

        llbl_date_to.setText("To:");

        button_search.setText("SEARCH");

        radioButton_requested.setText("Requested:");

        radioButton_all.setText("All:");

        jRadioButton3.setText("Received:");

        radioButton_read.setText("Read:");

        radioButton_processed.setText("Processed:");
        radioButton_processed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_processedActionPerformed(evt);
            }
        });

        txtF_requested.setEditable(false);

        lbl_from.setText("From:");

        lbl_date_since.setText("Since:");

        cbBox_from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de la tabla correspondiente" }));

        cbBox_To.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_optionsLayout = new javax.swing.GroupLayout(panel_options);
        panel_options.setLayout(panel_optionsLayout);
        panel_optionsLayout.setHorizontalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_title_requestCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(lbl_from)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbl_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbBox_To, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(lbl_date_since)
                                .addGap(31, 31, 31)
                                .addComponent(spinner_since, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(llbl_date_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinner_to, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(radioButton_requested, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtF_requested, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtF_read, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(radioButton_read, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtF_receved, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(radioButton_processed, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtF_processed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(radioButton_all)
                        .addGap(18, 18, 18)
                        .addComponent(txtF_all, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_search)))
                .addContainerGap())
        );
        panel_optionsLayout.setVerticalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_date_since)
                            .addComponent(spinner_since, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llbl_date_to)
                            .addComponent(spinner_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_from)
                            .addComponent(cbBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_to)
                            .addComponent(cbBox_To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_title_requestCategories)
                        .addGap(18, 18, 18)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_requested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioButton_requested)
                                    .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_read, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioButton_read)
                                    .addComponent(radioButton_processed)
                                    .addComponent(txtF_processed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioButton_all)
                                .addComponent(txtF_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtF_receved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout tab_requestsLayout = new javax.swing.GroupLayout(tab_requests);
        tab_requests.setLayout(tab_requestsLayout);
        tab_requestsLayout.setHorizontalGroup(
            tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_requestsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panel_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab_requestsLayout.setVerticalGroup(
            tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_requestsLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPane_inventory_actions.addTab("Requests", tab_requests);

        panel_searchOptions.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lbl_inventary_store.setText("Store:");

        cbBox_inventary_store.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lo obtendrás de una tabla" }));

        radioButton_inventory_WhiteLine.setText("White line");

        lbl_inventary_productCategory.setText("Category:");

        radioButton_inventary_BrownLine.setText("Brown line");

        lbl_inventary_productCode.setText("Code:");

        btn_inventary_search.setText("SEARCH");

        radioButton_inventory_EcoLine.setText("Eco line");

        lbl_inventary_productType.setText("Type:");

        cbBox_inventary_productType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All (lo demás lo sacas de una tabla)" }));

        lbl_inventary_productBrand.setText("Brand:");

        cbBox_inventory_productBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de la tabla" }));

        javax.swing.GroupLayout panel_searchOptionsLayout = new javax.swing.GroupLayout(panel_searchOptions);
        panel_searchOptions.setLayout(panel_searchOptionsLayout);
        panel_searchOptionsLayout.setHorizontalGroup(
            panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                        .addComponent(lbl_inventary_productCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_inventory_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_inventary_productBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_inventory_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                        .addComponent(lbl_inventary_productCategory)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_inventory_WhiteLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_inventary_BrownLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_inventory_EcoLine)
                        .addGap(41, 41, 41)
                        .addComponent(lbl_inventary_productType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_inventary_productType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_searchOptionsLayout.createSequentialGroup()
                        .addComponent(lbl_inventary_store)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBox_inventary_store, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_inventary_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        panel_searchOptionsLayout.setVerticalGroup(
            panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inventary_store)
                    .addComponent(cbBox_inventary_store, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inventary_productCode)
                    .addComponent(txt_inventory_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inventary_productBrand)
                    .addComponent(cbBox_inventory_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                        .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_inventary_productCategory)
                            .addComponent(radioButton_inventory_WhiteLine)
                            .addComponent(radioButton_inventary_BrownLine)
                            .addComponent(radioButton_inventory_EcoLine)
                            .addComponent(cbBox_inventary_productType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_inventary_productType))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_inventary_search, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        table_inventary_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Brand", "StockID", "Price", "Avaible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel_inventary_details.setViewportView(table_inventary_details);
        if (table_inventary_details.getColumnModel().getColumnCount() > 0) {
            table_inventary_details.getColumnModel().getColumn(0).setResizable(false);
            table_inventary_details.getColumnModel().getColumn(0).setPreferredWidth(73);
            table_inventary_details.getColumnModel().getColumn(1).setPreferredWidth(210);
            table_inventary_details.getColumnModel().getColumn(2).setResizable(false);
            table_inventary_details.getColumnModel().getColumn(2).setPreferredWidth(150);
            table_inventary_details.getColumnModel().getColumn(3).setResizable(false);
            table_inventary_details.getColumnModel().getColumn(3).setPreferredWidth(80);
            table_inventary_details.getColumnModel().getColumn(4).setResizable(false);
            table_inventary_details.getColumnModel().getColumn(4).setPreferredWidth(70);
            table_inventary_details.getColumnModel().getColumn(5).setResizable(false);
            table_inventary_details.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        btn_inventory_transfer.setText("Transfer");

        btn_inventory_add.setText("ADD");

        javax.swing.GroupLayout tab_inventoryLayout = new javax.swing.GroupLayout(tab_inventory);
        tab_inventory.setLayout(tab_inventoryLayout);
        tab_inventoryLayout.setHorizontalGroup(
            tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_searchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inventoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_inventory_add, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inventory_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab_inventoryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPanel_inventary_details, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(75, Short.MAX_VALUE)))
        );
        tab_inventoryLayout.setVerticalGroup(
            tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_inventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_searchOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_inventory_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inventory_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(570, Short.MAX_VALUE))
            .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inventoryLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(scrollPanel_inventary_details, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        tabbedPane_inventory_actions.addTab("Inventory", tab_inventory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane_inventory_actions)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane_inventory_actions)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButton_processedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_processedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_processedActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inventary_search;
    private javax.swing.JButton btn_inventory_add;
    private javax.swing.JButton btn_inventory_transfer;
    private javax.swing.JButton button_search;
    private javax.swing.JComboBox<String> cbBox_To;
    private javax.swing.JComboBox<String> cbBox_from;
    private javax.swing.JComboBox<String> cbBox_inventary_productType;
    private javax.swing.JComboBox<String> cbBox_inventary_store;
    private javax.swing.JComboBox<String> cbBox_inventory_productBrand;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_date_since;
    private javax.swing.JLabel lbl_from;
    private javax.swing.JLabel lbl_inventary_productBrand;
    private javax.swing.JLabel lbl_inventary_productCategory;
    private javax.swing.JLabel lbl_inventary_productCode;
    private javax.swing.JLabel lbl_inventary_productType;
    private javax.swing.JLabel lbl_inventary_store;
    private javax.swing.JLabel lbl_title_requestCategories;
    private javax.swing.JLabel lbl_to;
    private javax.swing.JLabel llbl_date_to;
    private javax.swing.JPanel panel_options;
    private javax.swing.JPanel panel_searchOptions;
    private javax.swing.JRadioButton radioButton_all;
    private javax.swing.JRadioButton radioButton_inventary_BrownLine;
    private javax.swing.JRadioButton radioButton_inventory_EcoLine;
    private javax.swing.JRadioButton radioButton_inventory_WhiteLine;
    private javax.swing.JRadioButton radioButton_processed;
    private javax.swing.JRadioButton radioButton_read;
    private javax.swing.JRadioButton radioButton_requested;
    private javax.swing.JScrollPane scrollPanel_inventary_details;
    private javax.swing.JSpinner spinner_since;
    private javax.swing.JSpinner spinner_to;
    private javax.swing.JPanel tab_inventory;
    private javax.swing.JPanel tab_requests;
    private javax.swing.JTabbedPane tabbedPane_inventory_actions;
    private javax.swing.JTable table_inventary_details;
    private javax.swing.JTable table_requests;
    private javax.swing.JTextField txtF_all;
    private javax.swing.JTextField txtF_processed;
    private javax.swing.JTextField txtF_read;
    private javax.swing.JTextField txtF_receved;
    private javax.swing.JTextField txtF_requested;
    private javax.swing.JTextField txt_inventory_productCode;
    // End of variables declaration//GEN-END:variables
}
