/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.Building.Stowage;

import Backend.DB.DAO.Stowage_DAO;
import Backend.DB.DTO.Employee_DTO;
import Backend.FrontendAuxiliar.TableAuxiliar;
import Backend.Tools.Tool;
import Frontend.Building.Inventary.Transfer.Movement;
import Frontend.Building.Product.Product;
import java.util.ArrayList;
import javax.swing.JComboBox;

/**
 *
 * @author phily
 */
public class Stowage_Content extends javax.swing.JInternalFrame{
    private Employee_DTO employee;
    
    private Product product_window;
    private Movement movement_window;
    
    private Stowage_DAO stowageDAO;
    private TableAuxiliar tableAux;
    private Tool tool;
    
    /**
     * Creates new form Store_Content
     */
    public Stowage_Content(Employee_DTO employee) {
        initComponents();
        
        this.employee = employee;
        
        this.stowageDAO = new Stowage_DAO();
        this.tableAux = new TableAuxiliar();
        this.tool = new Tool();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPan_inventoryOptions = new javax.swing.JTabbedPane();
        tab_requests = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_requests = new javax.swing.JTable();
        panel_options = new javax.swing.JPanel();
        lbl_title_requestCategories = new javax.swing.JLabel();
        txtF_read = new javax.swing.JTextField();
        txtF_processed = new javax.swing.JTextField();
        txtF_all = new javax.swing.JTextField();
        txtF_receved = new javax.swing.JTextField();
        lbl_to = new javax.swing.JLabel();
        llbl_date_to = new javax.swing.JLabel();
        button_search = new javax.swing.JButton();
        radioButton_requested = new javax.swing.JRadioButton();
        radioButton_all = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        radioButton_read = new javax.swing.JRadioButton();
        radioButton_processed = new javax.swing.JRadioButton();
        txtF_requested = new javax.swing.JTextField();
        lbl_from = new javax.swing.JLabel();
        lbl_date_since = new javax.swing.JLabel();
        cbBox_from = new javax.swing.JComboBox<>();
        cbBox_To = new javax.swing.JComboBox<>();
        spinner_since = new javax.swing.JSpinner();
        spinner_to = new javax.swing.JSpinner();
        tab_inventory = new javax.swing.JPanel();
        panel_searchOptions = new javax.swing.JPanel();
        lbl_inventaryStore = new javax.swing.JLabel();
        cbBox_inventaryStore = new javax.swing.JComboBox<>();
        radioButton_WhiteLine = new javax.swing.JRadioButton();
        lbl_inventaryCategory = new javax.swing.JLabel();
        radioButton_BrownLine = new javax.swing.JRadioButton();
        lbl_inventaryCode = new javax.swing.JLabel();
        txt_code = new javax.swing.JTextField();
        btn_inventarySearch = new javax.swing.JButton();
        radioButton_EcoLine = new javax.swing.JRadioButton();
        lbl_inventaryType = new javax.swing.JLabel();
        cbBox_InventaryType = new javax.swing.JComboBox<>();
        lbl_inventaryBrand = new javax.swing.JLabel();
        cbBox_brand = new javax.swing.JComboBox<>();
        scrollPanel_inventaryDetails = new javax.swing.JScrollPane();
        table_inventaryDetails = new javax.swing.JTable();
        btn_transfer = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        tbPane_StowageContent = new javax.swing.JTabbedPane();
        tab_Request = new javax.swing.JPanel();
        panel_especifications = new javax.swing.JPanel();
        lbl_from1 = new javax.swing.JLabel();
        cbBox_request_From = new javax.swing.JComboBox<>();
        lbl_to1 = new javax.swing.JLabel();
        cbBox_request_To = new javax.swing.JComboBox<>();
        panel_requestStates = new javax.swing.JPanel();
        radioButton_all1 = new javax.swing.JRadioButton();
        txtF_number_all = new javax.swing.JTextField();
        radioButton_received = new javax.swing.JRadioButton();
        radioButton_processed1 = new javax.swing.JRadioButton();
        txtF_number_recceived = new javax.swing.JTextField();
        txtF_number_processed = new javax.swing.JTextField();
        txtF_number_requested = new javax.swing.JTextField();
        txtF_number_read = new javax.swing.JTextField();
        radioButton_read1 = new javax.swing.JRadioButton();
        radioButton_requested1 = new javax.swing.JRadioButton();
        panel_filters = new javax.swing.JPanel();
        radioButton_inventory_requeredDate = new javax.swing.JRadioButton();
        radioButton_inventory_dateOfRequest = new javax.swing.JRadioButton();
        lbl_inventary_since = new javax.swing.JLabel();
        lbl_until = new javax.swing.JLabel();
        button_searchTransfer = new javax.swing.JLabel();
        Ftxt_until = new javax.swing.JFormattedTextField();
        Ftxt_since = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_requests1 = new javax.swing.JTable();
        tab_Stowage = new javax.swing.JPanel();
        scrollPanel_inventary_details = new javax.swing.JScrollPane();
        table_store_details = new javax.swing.JTable();
        button_transfer = new javax.swing.JLabel();
        button_add = new javax.swing.JLabel();
        panel_searchOptions1 = new javax.swing.JPanel();
        panel_store_especifications = new javax.swing.JPanel();
        cbBox_inventory_productBrand = new javax.swing.JComboBox<>();
        txt_store_productCode = new javax.swing.JTextField();
        lbl_store_productCode = new javax.swing.JLabel();
        lbl_inventary_productBrand = new javax.swing.JLabel();
        lbl_inventary_store = new javax.swing.JLabel();
        cbBox_inventary_store = new javax.swing.JComboBox<>();
        panel_store_category = new javax.swing.JPanel();
        lbl_inventary_productType = new javax.swing.JLabel();
        cbBox_inventary_productType = new javax.swing.JComboBox<>();
        radioButton_store_WhiteLine = new javax.swing.JRadioButton();
        radioButton_store_BrownLine = new javax.swing.JRadioButton();
        radioButton_store_PAE = new javax.swing.JRadioButton();
        radioButton_store_grayLine = new javax.swing.JRadioButton();
        button_store_search = new javax.swing.JLabel();
        button_update = new javax.swing.JLabel();

        table_requests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Date Requested", "Due Date", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_requests);

        lbl_title_requestCategories.setText("Request categories");

        txtF_read.setEditable(false);

        txtF_processed.setEditable(false);

        txtF_all.setEditable(false);

        txtF_receved.setEditable(false);

        lbl_to.setText("To:");

        llbl_date_to.setText("To:");

        button_search.setText("SEARCH");

        radioButton_requested.setText("Requested:");

        radioButton_all.setText("All:");

        jRadioButton3.setText("Received:");

        radioButton_read.setText("Read:");

        radioButton_processed.setText("Processed:");
        radioButton_processed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_processedActionPerformed(evt);
            }
        });

        txtF_requested.setEditable(false);

        lbl_from.setText("From:");

        lbl_date_since.setText("Since:");

        cbBox_from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de la tabla correspondiente" }));

        cbBox_To.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panel_optionsLayout = new javax.swing.GroupLayout(panel_options);
        panel_options.setLayout(panel_optionsLayout);
        panel_optionsLayout.setHorizontalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_title_requestCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(lbl_from)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbl_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbBox_To, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(lbl_date_since)
                                .addGap(31, 31, 31)
                                .addComponent(spinner_since, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(llbl_date_to)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spinner_to, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(radioButton_requested, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtF_requested, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtF_read, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(radioButton_read, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtF_receved, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addComponent(radioButton_processed, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtF_processed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(radioButton_all)
                        .addGap(18, 18, 18)
                        .addComponent(txtF_all, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_search)))
                .addContainerGap())
        );
        panel_optionsLayout.setVerticalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_date_since)
                            .addComponent(spinner_since, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(llbl_date_to)
                            .addComponent(spinner_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_search, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(panel_optionsLayout.createSequentialGroup()
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_from)
                            .addComponent(cbBox_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_to)
                            .addComponent(cbBox_To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_title_requestCategories)
                        .addGap(18, 18, 18)
                        .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_optionsLayout.createSequentialGroup()
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_requested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioButton_requested)
                                    .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtF_read, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radioButton_read)
                                    .addComponent(radioButton_processed)
                                    .addComponent(txtF_processed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioButton_all)
                                .addComponent(txtF_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtF_receved, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );

        javax.swing.GroupLayout tab_requestsLayout = new javax.swing.GroupLayout(tab_requests);
        tab_requests.setLayout(tab_requestsLayout);
        tab_requestsLayout.setHorizontalGroup(
            tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_requestsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(panel_options, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tab_requestsLayout.setVerticalGroup(
            tab_requestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_requestsLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabbedPan_inventoryOptions.addTab("Requests", tab_requests);

        lbl_inventaryStore.setText("Store:");

        cbBox_inventaryStore.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lo obtendrás de una tabla" }));

        radioButton_WhiteLine.setText("White line");

        lbl_inventaryCategory.setText("Category:");

        radioButton_BrownLine.setText("Brown line");

        lbl_inventaryCode.setText("Code:");

        btn_inventarySearch.setText("SEARCH");

        radioButton_EcoLine.setText("Eco line");

        lbl_inventaryType.setText("Type:");

        cbBox_InventaryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All (lo demás lo sacas de una tabla)" }));

        lbl_inventaryBrand.setText("Brand:");

        cbBox_brand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de la tabla" }));

        javax.swing.GroupLayout panel_searchOptionsLayout = new javax.swing.GroupLayout(panel_searchOptions);
        panel_searchOptions.setLayout(panel_searchOptionsLayout);
        panel_searchOptionsLayout.setHorizontalGroup(
            panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                        .addComponent(lbl_inventaryCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_inventaryBrand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 338, Short.MAX_VALUE)
                        .addComponent(lbl_inventaryStore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBox_inventaryStore, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                        .addComponent(lbl_inventaryCategory)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_WhiteLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_BrownLine)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_EcoLine)
                        .addGap(41, 41, 41)
                        .addComponent(lbl_inventaryType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbBox_InventaryType, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_inventarySearch)))
                .addGap(6, 6, 6))
        );
        panel_searchOptionsLayout.setVerticalGroup(
            panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inventaryStore)
                    .addComponent(cbBox_inventaryStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inventaryCode)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inventaryBrand)
                    .addComponent(cbBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_inventarySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_searchOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_inventaryCategory)
                        .addComponent(radioButton_WhiteLine)
                        .addComponent(radioButton_BrownLine)
                        .addComponent(radioButton_EcoLine)
                        .addComponent(cbBox_InventaryType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_inventaryType)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        table_inventaryDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Brand", "StockID", "Price", "Avaible"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanel_inventaryDetails.setViewportView(table_inventaryDetails);

        btn_transfer.setText("Transfer");

        btn_add.setText("ADD");

        javax.swing.GroupLayout tab_inventoryLayout = new javax.swing.GroupLayout(tab_inventory);
        tab_inventory.setLayout(tab_inventoryLayout);
        tab_inventoryLayout.setHorizontalGroup(
            tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_searchOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inventoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_transfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tab_inventoryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollPanel_inventaryDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );
        tab_inventoryLayout.setVerticalGroup(
            tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_inventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_searchOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(572, Short.MAX_VALUE))
            .addGroup(tab_inventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_inventoryLayout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(scrollPanel_inventaryDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        tabbedPan_inventoryOptions.addTab("Inventory", tab_inventory);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tab_Request.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tab_RequestFocusGained(evt);
            }
        });

        panel_especifications.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jamrul", 0, 13))); // NOI18N

        lbl_from1.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_from1.setText("From:");

        cbBox_request_From.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        lbl_to1.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_to1.setText("To:");

        cbBox_request_To.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N

        javax.swing.GroupLayout panel_especificationsLayout = new javax.swing.GroupLayout(panel_especifications);
        panel_especifications.setLayout(panel_especificationsLayout);
        panel_especificationsLayout.setHorizontalGroup(
            panel_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_especificationsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_from1)
                .addGap(18, 18, 18)
                .addComponent(cbBox_request_From, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lbl_to1)
                .addGap(26, 26, 26)
                .addComponent(cbBox_request_To, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        panel_especificationsLayout.setVerticalGroup(
            panel_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_especificationsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_from1)
                    .addComponent(cbBox_request_From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_to1)
                    .addComponent(cbBox_request_To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panel_requestStates.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Request states", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jamrul", 0, 13))); // NOI18N

        radioButton_all1.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_all1.setText("All:");

        txtF_number_all.setEditable(false);
        txtF_number_all.setFont(new java.awt.Font("Gayathri Thin", 0, 13)); // NOI18N

        radioButton_received.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_received.setText("Received:");

        radioButton_processed1.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_processed1.setText("Processed:");

        txtF_number_recceived.setEditable(false);
        txtF_number_recceived.setFont(new java.awt.Font("Gayathri Thin", 0, 13)); // NOI18N

        txtF_number_processed.setEditable(false);
        txtF_number_processed.setFont(new java.awt.Font("Gayathri Thin", 0, 13)); // NOI18N

        txtF_number_requested.setEditable(false);
        txtF_number_requested.setFont(new java.awt.Font("Gayathri Thin", 0, 13)); // NOI18N

        txtF_number_read.setEditable(false);
        txtF_number_read.setFont(new java.awt.Font("Gayathri Thin", 0, 13)); // NOI18N

        radioButton_read1.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_read1.setText("Read:");

        radioButton_requested1.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_requested1.setText("Requested:");

        javax.swing.GroupLayout panel_requestStatesLayout = new javax.swing.GroupLayout(panel_requestStates);
        panel_requestStates.setLayout(panel_requestStatesLayout);
        panel_requestStatesLayout.setHorizontalGroup(
            panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_requestStatesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButton_read1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_requestStatesLayout.createSequentialGroup()
                        .addComponent(radioButton_requested1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtF_number_read)
                            .addComponent(txtF_number_requested))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_requestStatesLayout.createSequentialGroup()
                        .addComponent(radioButton_received)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_requestStatesLayout.createSequentialGroup()
                        .addComponent(radioButton_processed1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtF_number_recceived)
                    .addComponent(txtF_number_processed, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(radioButton_all1)
                .addGap(18, 18, 18)
                .addComponent(txtF_number_all, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panel_requestStatesLayout.setVerticalGroup(
            panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_requestStatesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_requestStatesLayout.createSequentialGroup()
                        .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF_number_requested, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButton_requested1))
                        .addGap(18, 18, 18)
                        .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF_number_read, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButton_read1)))
                    .addGroup(panel_requestStatesLayout.createSequentialGroup()
                        .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioButton_all1)
                                .addComponent(txtF_number_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtF_number_processed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioButton_processed1)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_requestStatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF_number_recceived, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButton_received))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_filters.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jamrul", 0, 13))); // NOI18N

        radioButton_inventory_requeredDate.setText("Requered date");

        radioButton_inventory_dateOfRequest.setText("Date of request");

        lbl_inventary_since.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_inventary_since.setText("Since:");

        lbl_until.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_until.setText("Until:");

        button_searchTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SearchPlane.png"))); // NOI18N
        button_searchTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_searchTransferMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_filtersLayout = new javax.swing.GroupLayout(panel_filters);
        panel_filters.setLayout(panel_filtersLayout);
        panel_filtersLayout.setHorizontalGroup(
            panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filtersLayout.createSequentialGroup()
                .addGroup(panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_filtersLayout.createSequentialGroup()
                        .addGroup(panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_filtersLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(lbl_inventary_since))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_filtersLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_until)))
                        .addGap(18, 18, 18)
                        .addGroup(panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_searchTransfer)
                            .addComponent(Ftxt_until, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ftxt_since, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_filtersLayout.createSequentialGroup()
                        .addComponent(radioButton_inventory_dateOfRequest)
                        .addGap(18, 18, 18)
                        .addComponent(radioButton_inventory_requeredDate)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        panel_filtersLayout.setVerticalGroup(
            panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_filtersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton_inventory_requeredDate)
                    .addComponent(radioButton_inventory_dateOfRequest))
                .addGap(18, 18, 18)
                .addGroup(panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inventary_since)
                    .addComponent(Ftxt_since, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_filtersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_until)
                    .addComponent(Ftxt_until, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_searchTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        table_requests1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        table_requests1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "From", "To", "Date Requested", "Requered Date", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_requests1);

        javax.swing.GroupLayout tab_RequestLayout = new javax.swing.GroupLayout(tab_Request);
        tab_Request.setLayout(tab_RequestLayout);
        tab_RequestLayout.setHorizontalGroup(
            tab_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_RequestLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(tab_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(tab_RequestLayout.createSequentialGroup()
                        .addGroup(tab_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel_requestStates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_especifications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_filters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );
        tab_RequestLayout.setVerticalGroup(
            tab_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_RequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tab_RequestLayout.createSequentialGroup()
                        .addComponent(panel_especifications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_requestStates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_filters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tbPane_StowageContent.addTab("Request", tab_Request);

        tab_Stowage.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tab_StowageFocusGained(evt);
            }
        });

        table_store_details.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Brand", "StockID", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_store_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_store_detailsMouseClicked(evt);
            }
        });
        scrollPanel_inventary_details.setViewportView(table_store_details);
        if (table_store_details.getColumnModel().getColumnCount() > 0) {
            table_store_details.getColumnModel().getColumn(0).setResizable(false);
            table_store_details.getColumnModel().getColumn(0).setPreferredWidth(70);
            table_store_details.getColumnModel().getColumn(1).setPreferredWidth(210);
            table_store_details.getColumnModel().getColumn(2).setResizable(false);
            table_store_details.getColumnModel().getColumn(2).setPreferredWidth(200);
            table_store_details.getColumnModel().getColumn(3).setResizable(false);
            table_store_details.getColumnModel().getColumn(3).setPreferredWidth(70);
            table_store_details.getColumnModel().getColumn(4).setResizable(false);
            table_store_details.getColumnModel().getColumn(4).setPreferredWidth(50);
            table_store_details.getColumnModel().getColumn(5).setResizable(false);
            table_store_details.getColumnModel().getColumn(5).setPreferredWidth(70);
        }

        button_transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transfer.png"))); // NOI18N
        button_transfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_transferKeyPressed(evt);
            }
        });

        button_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        button_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_addMouseClicked(evt);
            }
        });

        panel_store_especifications.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Especifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jamrul", 0, 13))); // NOI18N

        cbBox_inventory_productBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));
        cbBox_inventory_productBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBox_inventory_productBrandActionPerformed(evt);
            }
        });

        lbl_store_productCode.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_store_productCode.setText("Code:");

        lbl_inventary_productBrand.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_inventary_productBrand.setText("Brand:");

        lbl_inventary_store.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_inventary_store.setText("Store:");

        cbBox_inventary_store.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBox_inventary_storeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_store_especificationsLayout = new javax.swing.GroupLayout(panel_store_especifications);
        panel_store_especifications.setLayout(panel_store_especificationsLayout);
        panel_store_especificationsLayout.setHorizontalGroup(
            panel_store_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_store_especificationsLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_store_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_store_productCode)
                    .addComponent(lbl_inventary_store))
                .addGroup(panel_store_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_store_especificationsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_store_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(panel_store_especificationsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbBox_inventary_store, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(lbl_inventary_productBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbBox_inventory_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        panel_store_especificationsLayout.setVerticalGroup(
            panel_store_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_store_especificationsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panel_store_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_store_productCode)
                    .addComponent(txt_store_productCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_store_especificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inventary_productBrand)
                    .addComponent(cbBox_inventory_productBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_inventary_store)
                    .addComponent(cbBox_inventary_store, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_store_category.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Jamrul", 0, 13))); // NOI18N

        lbl_inventary_productType.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        lbl_inventary_productType.setText("Type:");

        cbBox_inventary_productType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All" }));

        radioButton_store_WhiteLine.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_store_WhiteLine.setText("White line");

        radioButton_store_BrownLine.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_store_BrownLine.setText("Brown line");

        radioButton_store_PAE.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_store_PAE.setText("PAE");

        radioButton_store_grayLine.setFont(new java.awt.Font("Jamrul", 0, 13)); // NOI18N
        radioButton_store_grayLine.setText("Gray Line");

        javax.swing.GroupLayout panel_store_categoryLayout = new javax.swing.GroupLayout(panel_store_category);
        panel_store_category.setLayout(panel_store_categoryLayout);
        panel_store_categoryLayout.setHorizontalGroup(
            panel_store_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_store_categoryLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panel_store_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_store_categoryLayout.createSequentialGroup()
                        .addComponent(lbl_inventary_productType)
                        .addGap(18, 18, 18)
                        .addComponent(cbBox_inventary_productType, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_store_categoryLayout.createSequentialGroup()
                        .addComponent(radioButton_store_WhiteLine)
                        .addGap(26, 26, 26)
                        .addComponent(radioButton_store_BrownLine)
                        .addGap(26, 26, 26)
                        .addComponent(radioButton_store_PAE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(radioButton_store_grayLine)
                        .addGap(22, 22, 22))))
        );
        panel_store_categoryLayout.setVerticalGroup(
            panel_store_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_store_categoryLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panel_store_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_inventary_productType)
                    .addComponent(cbBox_inventary_productType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_store_categoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton_store_WhiteLine)
                    .addComponent(radioButton_store_BrownLine)
                    .addComponent(radioButton_store_PAE)
                    .addComponent(radioButton_store_grayLine))
                .addGap(15, 15, 15))
        );

        button_store_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SearchVertical.png"))); // NOI18N
        button_store_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_store_searchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_searchOptions1Layout = new javax.swing.GroupLayout(panel_searchOptions1);
        panel_searchOptions1.setLayout(panel_searchOptions1Layout);
        panel_searchOptions1Layout.setHorizontalGroup(
            panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptions1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panel_store_especifications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_store_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_store_search)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_searchOptions1Layout.setVerticalGroup(
            panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_searchOptions1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_searchOptions1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_store_especifications, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_store_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_searchOptions1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_store_search, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        button_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update.png"))); // NOI18N
        button_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_updateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tab_StowageLayout = new javax.swing.GroupLayout(tab_Stowage);
        tab_Stowage.setLayout(tab_StowageLayout);
        tab_StowageLayout.setHorizontalGroup(
            tab_StowageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_StowageLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(scrollPanel_inventary_details)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab_StowageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_update, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_add, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_transfer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
            .addComponent(panel_searchOptions1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tab_StowageLayout.setVerticalGroup(
            tab_StowageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_StowageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_searchOptions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(tab_StowageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_StowageLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(button_add)
                        .addGap(18, 18, 18)
                        .addComponent(button_update)
                        .addGap(18, 18, 18)
                        .addComponent(button_transfer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tab_StowageLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrollPanel_inventary_details, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        tbPane_StowageContent.addTab("Stowage", tab_Stowage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPane_StowageContent)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbPane_StowageContent, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButton_processedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_processedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButton_processedActionPerformed

    //-----INVENTARY-Tab
    
    private void tab_StowageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tab_StowageFocusGained
        ArrayList<String> offices = this.stowageDAO.getOfficeDAO().searchAll();
        ArrayList<String> brands = this.stowageDAO.getBrands();
        ArrayList<String> types = this.stowageDAO.getTypes();
        
        this.trasnferBraTypTocbBox(offices, this.cbBox_inventary_store);
        this.trasnferBraTypTocbBox(brands, this.cbBox_inventory_productBrand);        
        this.trasnferBraTypTocbBox(types, this.cbBox_inventary_productType);  
    }//GEN-LAST:event_tab_StowageFocusGained

    private void cbBox_inventary_storeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBox_inventary_storeActionPerformed
         //aquí el jueguito de las Brand según store                
        ArrayList<String> brands;
        ArrayList<String> types;
        
        if(this.cbBox_inventary_store.getSelectedIndex() == 0){// = All
            brands = this.stowageDAO.getBrands();
            types = this.stowageDAO.getTypes();
        }else{
            brands = this.stowageDAO.getMovUI_DAO()
                               .search_StoresBrand((String) this.cbBox_inventary_store
                                       .getSelectedItem());
            types = this.stowageDAO.getMovUI_DAO()
                               .list_BrandsTypes((String) this.cbBox_inventary_store
                                       .getSelectedItem());
        }
        
        this.trasnferBraTypTocbBox(brands, this.cbBox_inventory_productBrand);
        this.trasnferBraTypTocbBox(types, this.cbBox_inventary_productType);      
    }//GEN-LAST:event_cbBox_inventary_storeActionPerformed

    private void cbBox_inventory_productBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBox_inventory_productBrandActionPerformed
        //aquí el jueguito de los Type según Brand
        ArrayList<String> types;
        
        if(this.cbBox_inventory_productBrand.getSelectedIndex() == 0){// = All
            if(this.cbBox_inventary_store.getSelectedIndex() == 0){
                types = this.stowageDAO.getTypes();
            }else{
                types = this.stowageDAO.getMovUI_DAO()
                               .list_BrandsTypes((String) this.cbBox_inventary_store
                                       .getSelectedItem());
            }            
        }else{
            if(this.cbBox_inventary_store.getSelectedIndex() == 0){
                types = this.stowageDAO.getMovUI_DAO()
                      .list_Brands_Types((String)this.cbBox_inventory_productBrand
                            .getSelectedItem(), null);
            }else{
                types = this.stowageDAO.getMovUI_DAO()
                      .list_Brands_Types((String)this.cbBox_inventory_productBrand
                            .getSelectedItem(), (String) this.cbBox_inventary_store
                                       .getSelectedItem());
            }            
        }
        
        this.trasnferBraTypTocbBox(types, this.cbBox_inventary_productType);        
    }//GEN-LAST:event_cbBox_inventory_productBrandActionPerformed

    private void button_store_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_store_searchMouseClicked
         this.tableAux.setInventaryTab(this.table_inventaryDetails, 
            this.stowageDAO.getEmployee_IntDAO().searchOnInventary(
                ((!this.txt_store_productCode.getText().isEmpty() || !this.txt_store_productCode.getText().isBlank())
                    ?this.txt_store_productCode.getText():null),
                (String)this.cbBox_inventary_store.getSelectedItem(),
                (String)this.cbBox_inventory_productBrand.getSelectedItem(),
                (String)this.cbBox_inventary_productType.getSelectedItem(),
                this.setLines()));
    }//GEN-LAST:event_button_store_searchMouseClicked

    //--- (REQUEST- tab (pero ahora si de transfer xD, no solo de búsqueda)
    
    private void tab_RequestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tab_RequestFocusGained
        this.trasnferBraTypTocbBox(this.stowageDAO.getOfficeDAO().searchAll(), cbBox_request_From);
        this.trasnferBraTypTocbBox(this.stowageDAO.getOfficeDAO().searchAll(), cbBox_request_To);
        
        this.txtF_requested.setText(String.valueOf(this.stowageDAO.getTransferDAO().searchQuantityOf("pending")));
        this.txtF_requested.setText(String.valueOf(this.stowageDAO.getTransferDAO().searchQuantityOf("read")));
        this.txtF_requested.setText(String.valueOf(this.stowageDAO.getTransferDAO().searchQuantityOf("processed")));
        this.txtF_requested.setText(String.valueOf(this.stowageDAO.getTransferDAO().searchQuantityOf("done")));
        this.txtF_requested.setText(String.valueOf(this.stowageDAO.getTransferDAO().searchQuantityOf(null)));        
        
    }//GEN-LAST:event_tab_RequestFocusGained
    
    private void button_searchTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_searchTransferMouseClicked
        String[] dates = this.setDates();
        String[] dateTypes = this.setFilterDates();
        
        if(dates == null || dateTypes == null){
            this.tableAux.setTransferTable(this.table_requests1,
                    this.stowageDAO.getInvStow_In_DAO()
                        .searchTransfers(((String)this.cbBox_from.getSelectedItem()),
                                ((String)this.cbBox_To.getSelectedItem()), 
                                this.setStates(),
                                ((dateTypes == null || dates == null)?null:dateTypes),
                                ((dateTypes == null || dates == null)?null:dates)));            
        }
    }//GEN-LAST:event_button_searchTransferMouseClicked

    private void button_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addMouseClicked
        this.product_window = new Product(this.employee.getContract().getOffice(), 1,
                false, null, this.stowageDAO);
    }//GEN-LAST:event_button_addMouseClicked

    private void button_updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_updateMouseClicked
        this.product_window = new Product(this.employee.getContract().getOffice(), 2,
                false, null, this.stowageDAO);
    }//GEN-LAST:event_button_updateMouseClicked

    private void button_transferKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_transferKeyPressed
        this.movement_window = new Movement();// TODO add your handling code here:
        
        //also you can open this window just as a viewer doing 2ble click on a row of athe correspondent table        
    }//GEN-LAST:event_button_transferKeyPressed

    private void table_store_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_store_detailsMouseClicked
        //este será utilizado para VER
        int row = this.table_store_details.getSelectedRow();
        if(row != -1){
            this.product_window 
               = new Product(((Long)this.table_store_details.getValueAt(row, 1)),
                       this.employee.getContract().getOffice(), 3, true, null, this.stowageDAO);
            this.product_window.setLocationRelativeTo(null);
            this.product_window.setVisible(true);
        }//VIEW, ready     
    }//GEN-LAST:event_table_store_detailsMouseClicked

    
    //---- AUXILIARIES
    
    private void trasnferBraTypTocbBox(ArrayList<String> list, JComboBox cbBox){
        for (int i = 0; i < list.size(); i++) {
            if(i == 0){
                cbBox.addItem("all");
            }else{
                cbBox.addItem(list.get(i));
            }
        }   
    }

    //----- para lineas de los elctrodométicos
    
    private String[] setLines(){
        ArrayList<String> arrayList = new ArrayList<>();
        
        if(this.radioButton_store_WhiteLine.isSelected() && this.radioButton_store_grayLine.isSelected()
            && this.radioButton_store_BrownLine.isSelected() && this.radioButton_store_PAE.isSelected()){
            arrayList.add("all");
        }else if(this.radioButton_store_WhiteLine.isSelected()){
            arrayList.add("White Line");
        }else if(this.radioButton_store_BrownLine.isSelected()){
            arrayList.add("Brown Line");
        }else if(this.radioButton_store_PAE.isSelected()){
            arrayList.add("PAE");
        }else if(this.radioButton_store_grayLine.isSelected()){
            arrayList.add("Gray Line");
        }else{
            arrayList.add("all");//puesto que no seleccionó ninguna tb significa que todas xD
        }   
        
        if(arrayList.isEmpty()){
            return null;
        }
        return (String[]) arrayList.toArray();
    }
    
    //---- Estos 3 son para hacer la búsqueda de las TRANSFER
    
    private String[] setStates(){
        ArrayList<String> arrayList = new ArrayList<>();
        
        if((this.radioButton_requested1.isSelected() && this.radioButton_read1.isSelected()
            && this.radioButton_processed1.isSelected() && this.radioButton_received.isSelected())
            || this.radioButton_all.isSelected()){
            arrayList.add("all");
        }else if(this.radioButton_requested1.isSelected()){
            arrayList.add("pending");
        }else if(this.radioButton_read1.isSelected()){
            arrayList.add("read");
        }else if(this.radioButton_processed1.isSelected()){
            arrayList.add("processed");
        }else if(this.radioButton_received.isSelected()){
            arrayList.add("done");
        }else{//si no seleccionana algo tn es atrasp xd
            arrayList.add("all");//puesto que no seleccionó ninguna tb significa que todas xD
        }
        
        if(arrayList.isEmpty()){
            return null;
        }
        return (String[]) arrayList.toArray();
    }
    
    private String[] setFilterDates(){
        ArrayList<String> arrayList = new ArrayList<>();
        
        if(this.radioButton_inventory_dateOfRequest.isSelected()){
            arrayList.add(this.radioButton_inventory_dateOfRequest.getText());
        }
        if(this.radioButton_inventory_requeredDate.isSelected()){
            arrayList.add(this.radioButton_inventory_requeredDate.getText());
        }
        
        if(arrayList.isEmpty()){
            return null;
        }
        return (String[]) arrayList.toArray();//devolverá null si no hay ninguno de ambos
    }
    
    private String[] setDates(){
        ArrayList<String> arrayList = new ArrayList<>();
        
        if(!this.Ftxt_since.getText().equals("")){
            arrayList.add(this.Ftxt_since.getText());
        }
        if(!this.Ftxt_until.getText().equals("")){
            arrayList.add(this.Ftxt_until.getText());
        }        
        
        if(arrayList.isEmpty()){
            return null;
        }
        return (String[]) arrayList.toArray();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Ftxt_since;
    private javax.swing.JFormattedTextField Ftxt_until;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_inventarySearch;
    private javax.swing.JButton btn_transfer;
    private javax.swing.JLabel button_add;
    private javax.swing.JButton button_search;
    private javax.swing.JLabel button_searchTransfer;
    private javax.swing.JLabel button_store_search;
    private javax.swing.JLabel button_transfer;
    private javax.swing.JLabel button_update;
    private javax.swing.JComboBox<String> cbBox_InventaryType;
    private javax.swing.JComboBox<String> cbBox_To;
    private javax.swing.JComboBox<String> cbBox_brand;
    private javax.swing.JComboBox<String> cbBox_from;
    private javax.swing.JComboBox<String> cbBox_inventaryStore;
    private javax.swing.JComboBox<String> cbBox_inventary_productType;
    private javax.swing.JComboBox<String> cbBox_inventary_store;
    private javax.swing.JComboBox<String> cbBox_inventory_productBrand;
    private javax.swing.JComboBox<String> cbBox_request_From;
    private javax.swing.JComboBox<String> cbBox_request_To;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_date_since;
    private javax.swing.JLabel lbl_from;
    private javax.swing.JLabel lbl_from1;
    private javax.swing.JLabel lbl_inventaryBrand;
    private javax.swing.JLabel lbl_inventaryCategory;
    private javax.swing.JLabel lbl_inventaryCode;
    private javax.swing.JLabel lbl_inventaryStore;
    private javax.swing.JLabel lbl_inventaryType;
    private javax.swing.JLabel lbl_inventary_productBrand;
    private javax.swing.JLabel lbl_inventary_productType;
    private javax.swing.JLabel lbl_inventary_since;
    private javax.swing.JLabel lbl_inventary_store;
    private javax.swing.JLabel lbl_store_productCode;
    private javax.swing.JLabel lbl_title_requestCategories;
    private javax.swing.JLabel lbl_to;
    private javax.swing.JLabel lbl_to1;
    private javax.swing.JLabel lbl_until;
    private javax.swing.JLabel llbl_date_to;
    private javax.swing.JPanel panel_especifications;
    private javax.swing.JPanel panel_filters;
    private javax.swing.JPanel panel_options;
    private javax.swing.JPanel panel_requestStates;
    private javax.swing.JPanel panel_searchOptions;
    private javax.swing.JPanel panel_searchOptions1;
    private javax.swing.JPanel panel_store_category;
    private javax.swing.JPanel panel_store_especifications;
    private javax.swing.JRadioButton radioButton_BrownLine;
    private javax.swing.JRadioButton radioButton_EcoLine;
    private javax.swing.JRadioButton radioButton_WhiteLine;
    private javax.swing.JRadioButton radioButton_all;
    private javax.swing.JRadioButton radioButton_all1;
    private javax.swing.JRadioButton radioButton_inventory_dateOfRequest;
    private javax.swing.JRadioButton radioButton_inventory_requeredDate;
    private javax.swing.JRadioButton radioButton_processed;
    private javax.swing.JRadioButton radioButton_processed1;
    private javax.swing.JRadioButton radioButton_read;
    private javax.swing.JRadioButton radioButton_read1;
    private javax.swing.JRadioButton radioButton_received;
    private javax.swing.JRadioButton radioButton_requested;
    private javax.swing.JRadioButton radioButton_requested1;
    private javax.swing.JRadioButton radioButton_store_BrownLine;
    private javax.swing.JRadioButton radioButton_store_PAE;
    private javax.swing.JRadioButton radioButton_store_WhiteLine;
    private javax.swing.JRadioButton radioButton_store_grayLine;
    private javax.swing.JScrollPane scrollPanel_inventaryDetails;
    private javax.swing.JScrollPane scrollPanel_inventary_details;
    private javax.swing.JSpinner spinner_since;
    private javax.swing.JSpinner spinner_to;
    private javax.swing.JPanel tab_Request;
    private javax.swing.JPanel tab_Stowage;
    private javax.swing.JPanel tab_inventory;
    private javax.swing.JPanel tab_requests;
    private javax.swing.JTabbedPane tabbedPan_inventoryOptions;
    private javax.swing.JTable table_inventaryDetails;
    private javax.swing.JTable table_requests;
    private javax.swing.JTable table_requests1;
    private javax.swing.JTable table_store_details;
    private javax.swing.JTabbedPane tbPane_StowageContent;
    private javax.swing.JTextField txtF_all;
    private javax.swing.JTextField txtF_number_all;
    private javax.swing.JTextField txtF_number_processed;
    private javax.swing.JTextField txtF_number_read;
    private javax.swing.JTextField txtF_number_recceived;
    private javax.swing.JTextField txtF_number_requested;
    private javax.swing.JTextField txtF_processed;
    private javax.swing.JTextField txtF_read;
    private javax.swing.JTextField txtF_receved;
    private javax.swing.JTextField txtF_requested;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_store_productCode;
    // End of variables declaration//GEN-END:variables
}
